title: Healthcare Domain Conference Deadlines
description: Displays Healthcare domain conferences deadline
author: 

domain: ""
baseurl: "/"
copyurl: "https://phddeadlines.github.io"

twitter_hashtag: 
github_username: phddeadlines
github_repo: phddeadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
